all:
	@echo "\x1B[0;1;35m [  MAKE ]\x1B[0m servers/fs/vfs"
	@make -C vfs

install:
	@echo "\x1B[0;1;35m [  MAKE ]\x1B[0m install servers/fs/vfs"
	@make install -C vfs

clean:
	@echo "\x1B[0;1;35m [  MAKE ]\x1B[0m clean servers/fs/vfs"
	@make clean -C vfs
