all:
	@echo "\x1B[0;1;35m make\x1B[0m servers/devices/ps2"
	@make -C ps2

install:
	@echo "\x1B[0;1;35m make\x1B[0m install servers/devices/ps2"
	@make install -C ps2

clean:
	@echo "\x1B[0;1;35m make\x1B[0m clean servers/devices/ps2"
	@make clean -C ps2
