all:
	@echo "\x1B[0;1;35m make\x1B[0m servers/devices/ps2"
	@make -C ps2
	@echo "\x1B[0;1;35m make\x1B[0m servers/devices/kbd"
	@make -C kbd

install:
	@echo "\x1B[0;1;35m make\x1B[0m install servers/devices/ps2"
	@make install -C ps2
	@echo "\x1B[0;1;35m make\x1B[0m install servers/devices/kbd"
	@make install -C kbd

clean:
	@echo "\x1B[0;1;35m make\x1B[0m clean servers/devices/ps2"
	@make clean -C ps2
	@echo "\x1B[0;1;35m make\x1B[0m clean servers/devices/kbd"
	@make clean -C kbd
