all:
	@echo "\x1B[0;1;35m make\x1B[0m servers/devices/sdev/nvme"
	@make -C nvme

install:
	@echo "\x1B[0;1;35m make\x1B[0m install servers/devices/nvme"
	@make install -C nvme

clean:
	@echo "\x1B[0;1;35m make\x1B[0m clean servers/devices/nvme"
	@make clean -C nvme
